# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/STARKer-first/Desktop/COD/fpgaol1.xdc

# IP: ip/instruction_mem/instruction_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==instruction_mem || ORIG_REF_NAME==instruction_mem} -quiet] -quiet

# IP: ip/data_mem/data_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_mem || ORIG_REF_NAME==data_mem} -quiet] -quiet

# XDC: c:/Users/STARKer-first/Desktop/COD/lab4/project_1/project_1.gen/sources_1/ip/data_mem/data_mem_ooc.xdc
