# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/STARKer-first/Desktop/COD/lab6/project_1/project_1.srcs/sources_1/ip/instruction_mem/instruction_mem.xci
# IP: The module: 'instruction_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/STARKer-first/Desktop/COD/lab6/project_1/project_1.gen/sources_1/ip/instruction_mem/instruction_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/STARKer-first/Desktop/COD/lab6/project_1/project_1.srcs/sources_1/ip/instruction_mem/instruction_mem.xci
# IP: The module: 'instruction_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/STARKer-first/Desktop/COD/lab6/project_1/project_1.gen/sources_1/ip/instruction_mem/instruction_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
